name: Delivery

on:
  deployment:
    types: [created] # Garante que o workflow é acionado quando um deployment é criado

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        uses: deliverybot/helm@v1
        with:
          release: 'nginx'
          namespace: 'default'
          chart: 'app'
          token: ${{ secrets.GITHUB_TOKEN }} # Usa o token correto para a autenticação
          values: |
            name: foobar
          value-files: |
            values.yaml
            values.production.yaml
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
