name: Deploy

on:
  push: 
    branches: 
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x # Atualize para uma versão mais recente se necessário

      - name: Deployment pending
        uses: deliverybot/deployment-status@v1
        with:
          state: 'pending'
          token: ${{ secrets.GITHUB_TOKEN }} # Use o segredo correto para o token

      - name: Deploy
        run: npm run deploy

      - name: Deployment success
        if: success()
        uses: deliverybot/deployment-status@v1
        with:
          state: 'success'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deployment failure
        if: failure()
        uses: deliverybot/deployment-status@v1
        with:
          state: 'failure'
          token: ${{ secrets.GITHUB_TOKEN }}
