name: Continuous Delivery-Dogs

on:
  pull_request:
    branches:
      - main

jobs:
  deliver:
    name: Run Action Dogs
    runs-on: ubuntu-latest

    steps:

      - name: Doggoes as an Action
        uses: stanleynguyen/action-dogs@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
